const giftData = [
    { name: "Love Letter Kit", isUnder20: true, type: "romantic" },
    { name: "Date Night Cookbook", isUnder20: true, type: "romantic" },
    { name: "His & Hers Coffee Mugs", isUnder20: true, type: "romantic" },
    { name: "Personalized Photo Album", isUnder20: false, type: "romantic" },
    { name: "Couple's Bathrobe Set", isUnder20: false, type: "romantic" },
    { name: "Heart-Shaped Tea Infuser", isUnder20: true, type: "romantic" },
    { name: "Romantic Movie Night Kit", isUnder20: false, type: "romantic" },
    { name: "Couples' Game Set", isUnder20: true, type: "romantic" },
    { name: "Love Coupons", isUnder20: true, type: "romantic" },
    { name: "Scented Candle Gift Set", isUnder20: false, type: "romantic" },
    { name: "Love Poem Book", isUnder20: true, type: "romantic" },
    { name: "Message in a Bottle", isUnder20: true, type: "romantic" },
    { name: "Personalized Photo Puzzle", isUnder20: false, type: "romantic" },
    { name: "His & Hers Keychains", isUnder20: true, type: "romantic" },
    { name: "Couple's Memory Jar", isUnder20: true, type: "romantic" },
    { name: "Date Night Jar", isUnder20: true, type: "romantic" },
    { name: "Couple's Cookbook", isUnder20: false, type: "romantic" },
    { name: "Personalized Song Lyrics Print", isUnder20: false, type: "romantic" },
    { name: "Couple's Initial Bracelets", isUnder20: true, type: "romantic" },
    { name: "Romantic Scrapbook", isUnder20: false, type: "romantic" },
    { name: "Date Night Dice", isUnder20: true, type: "romantic" },
    { name: "Couple's Yoga Mat", isUnder20: false, type: "romantic" },
    { name: "Romantic Picture Frame", isUnder20: true, type: "romantic" },
    { name: "His & Hers Robes", isUnder20: false, type: "romantic" },
    { name: "Couple's Love Story Book", isUnder20: false, type: "romantic" },
    { name: "Engraved Wine Glasses", isUnder20: true, type: "romantic" },
    { name: "Couple's Puzzle Necklace Set", isUnder20: false, type: "romantic" },
    { name: "Love Quote Wall Art", isUnder20: true, type: "romantic" },
    { name: "Date Night Board Game", isUnder20: false, type: "romantic" },
    { name: "Couple's Travel Mug Set", isUnder20: true, type: "romantic" },
    { name: "Toilet Golf Game", isUnder20: true, type: "silly" },
    { name: "Farting Animals Coloring Book", isUnder20: true, type: "silly" },
    { name: "Inflatable Sumo Wrestler Costume", isUnder20: false, type: "silly" },
    { name: "Silly Coffee Mug", isUnder20: true, type: "silly" },
    { name: "Novelty Socks", isUnder20: true, type: "silly" },
    { name: "Inflatable Moose Head", isUnder20: false, type: "silly" },
    { name: "Squirrel in Underpants Air Freshener", isUnder20: true, type: "silly" },
    { name: "Rubber Chicken Keychain", isUnder20: true, type: "silly" },
    { name: "Desktop Tetherball Set", isUnder20: false, type: "silly" },
    { name: "Silly Desk Name Plate", isUnder20: true, type: "silly" },
    { name: "Pizza Socks", isUnder20: true, type: "silly" },
    { name: "Crazy Cat Lady Action Figure", isUnder20: false, type: "silly" },
    { name: "Inflatable Unicorn Horn for Cats", isUnder20: true, type: "silly" },
    { name: "Bacon Scented Candle", isUnder20: true, type: "silly" },
    { name: "Alien Headphones", isUnder20: false, type: "silly" },
    { name: "Inflatable Moose Antlers", isUnder20: true, type: "silly" },
    { name: "Silly Desk Toy", isUnder20: true, type: "silly" },
    { name: "Toilet Bowl Night Light", isUnder20: true, type: "silly" },
    { name: "Googly Eye Glasses", isUnder20: true, type: "silly" },
    { name: "Giant Wine Glass", isUnder20: false, type: "silly" },
    { name: "Gnome Garden Kit", isUnder20: true, type: "silly" },
    { name: "Silly Doormat", isUnder20: true, type: "silly" },
    { name: "Inflatable Zimmer Frame", isUnder20: false, type: "silly" },
    { name: "Inflatable Unicorn Horn for Humans", isUnder20: true, type: "silly" },
    { name: "Couch Potato TV Remote Control Holder", isUnder20: true, type: "silly" },
    { name: "Bald Eagle Socks", isUnder20: true, type: "silly" },
    { name: "Potty Putter Toilet Golf", isUnder20: true, type: "silly" },
    { name: "Silly Bathroom Sign", isUnder20: true, type: "silly" },
    { name: "Toilet Paper Blaster", isUnder20: false, type: "silly" },
    { name: "Giraffe Toilet Roll Holder", isUnder20: true, type: "silly" },
    { name: "Reusable Silicone Food Bags", isUnder20: false, type: "practical" },
    { name: "Wireless Phone Charger", isUnder20: false, type: "practical" },
    { name: "Multi-Tool Keychain", isUnder20: true, type: "practical" },
    { name: "Stainless Steel Water Bottle", isUnder20: false, type: "practical" },
    { name: "LED Desk Lamp", isUnder20: false, type: "practical" },
    { name: "Portable Phone Charger", isUnder20: false, type: "practical" },
    { name: "Smartphone Projector", isUnder20: false, type: "practical" },
    { name: "Adjustable Laptop Stand", isUnder20: false, type: "practical" },
    { name: "USB Flash Drive", isUnder20: true, type: "practical" },
    { name: "Sleep Mask", isUnder20: true, type: "practical" },
    { name: "Cord Organizer", isUnder20: true, type: "practical" },
    { name: "Reusable Coffee Cup", isUnder20: false, type: "practical" },
    { name: "Wireless Earbuds", isUnder20: false, type: "practical" },
    { name: "Electric Wine Bottle Opener", isUnder20: false, type: "practical" },
    { name: "Stainless Steel Straws", isUnder20: true, type: "practical" },
    { name: "Silicone Baking Mat", isUnder20: true, type: "practical" },
    { name: "Compact Umbrella", isUnder20: true, type: "practical" },
    { name: "Touch Screen Gloves", isUnder20: true, type: "practical" },
    { name: "Reusable Grocery Bags", isUnder20: true, type: "practical" },
    { name: "Bluetooth Headphones", isUnder20: false, type: "practical" },
    { name: "Reusable Water Bottle with Infuser", isUnder20: false, type: "practical" },
    { name: "Desk Organizer", isUnder20: true, type: "practical" },
    { name: "Packing Cubes", isUnder20: false, type: "practical" },
    { name: "Portable Blender", isUnder20: false, type: "practical" },
    { name: "LED Headlamp", isUnder20: true, type: "practical" },
    { name: "Electric Kettle", isUnder20: false, type: "practical" },
    { name: "Travel Adapter", isUnder20: true, type: "practical" },
    { name: "Reusable Tea Infuser", isUnder20: true, type: "practical" },
    { name: "Magnetic Phone Mount for Car", isUnder20: true, type: "practical" },
    { name: "Collapsible Water Bottle", isUnder20: true, type: "practical" },
    { name: "Electric Toothbrush", isUnder20: false, type: "practical" },
    { name: "Adjustable Dumbbells", isUnder20: false, type: "practical" },
    { name: "Bluetooth Speaker", isUnder20: false, type: "practical" },
    { name: "Handheld Steamer", isUnder20: false, type: "practical" },
    { name: "Wireless Charging Pad", isUnder20: true, type: "practical" },
    { name: "Portable Bluetooth Keyboard", isUnder20: true, type: "practical" },
    { name: "Tea Infuser Bottle", isUnder20: true, type: "practical" },
    { name: "Mini Portable Vacuum Cleaner", isUnder20: true, type: "practical" },
    { name: "Phone Tripod", isUnder20: true, type: "practical" },
    { name: "Wireless Earbuds Case", isUnder20: true, type: "practical" },
    { name: "Star Wars Lightsaber Chopsticks", isUnder20: true, type: "geeky" },
    { name: "Harry Potter Golden Snitch Fidget Spinner", isUnder20: true, type: "geeky" },
    { name: "Marvel Comics Superhero Socks", isUnder20: true, type: "geeky" },
    { name: "Doctor Who Sonic Screwdriver Pen", isUnder20: true, type: "geeky" },
    { name: "Super Mario Bros Heat Change Mug", isUnder20: true, type: "geeky" },
    { name: "Lego Brick Building Mug", isUnder20: true, type: "geeky" },
    { name: "Marvel Comics Iron Man USB Flash Drive", isUnder20: true, type: "geeky" },
    { name: "Star Trek Communicator Badge", isUnder20: true, type: "geeky" },
    { name: "The Big Bang Theory Trivia Game", isUnder20: true, type: "geeky" },
    { name: "NASA Logo T-shirt", isUnder20: true, type: "geeky" },
    { name: "Pac-Man Ghost Lamp", isUnder20: true, type: "geeky" },
    { name: "Game of Thrones Dragon Egg Collectibles", isUnder20: true, type: "geeky" },
    { name: "Doctor Who Tardis Keychain", isUnder20: true, type: "geeky" },
    { name: "Star Wars R2-D2 USB Car Charger", isUnder20: true, type: "geeky" },
    { name: "Batman Logo Projection Alarm Clock", isUnder20: true, type: "geeky" },
    { name: "Harry Potter Magic Wand Remote Control", isUnder20: false, type: "geeky" },
    { name: "Super Mario Bros Question Block Night Light", isUnder20: true, type: "geeky" },
    { name: "Marvel Comics Iron Man Headphones", isUnder20: true, type: "geeky" },
    { name: "Star Trek Enterprise Pizza Cutter", isUnder20: true, type: "geeky" },
    { name: "The Lord of the Rings One Ring Coffee Mug", isUnder20: true, type: "geeky" },
    { name: "Doctor Who Tardis Teapot", isUnder20: true, type: "geeky" },
    { name: "Star Wars Millennium Falcon Bottle Opener", isUnder20: true, type: "geeky" },
    { name: "Game of Thrones House Sigil Coasters", isUnder20: true, type: "geeky" },
    { name: "Harry Potter House Scarf", isUnder20: true, type: "geeky" },
    { name: "Super Mario Bros Shaped Mug", isUnder20: true, type: "geeky" },
    { name: "Marvel Comics Avengers Laptop Sleeve", isUnder20: true, type: "geeky" },
    { name: "Star Trek U.S.S. Enterprise Blueprint Poster", isUnder20: true, type: "geeky" },
    { name: "Doctor Who Tardis Hoodie", isUnder20: false, type: "geeky" },
    { name: "Star Wars Death Star Waffle Maker", isUnder20: false, type: "geeky" },
    { name: "Harry Potter Marauder's Map Heat Changing Mug", isUnder20: true, type: "geeky" },
    { name: "Super Mario Bros Question Block Lamp", isUnder20: true, type: "geeky" },
    { name: "Marvel Comics Iron Man Mini Fridge", isUnder20: false, type: "geeky" },
    { name: "Star Trek Inflatable Captain's Chair", isUnder20: false, type: "geeky" },
    { name: "The Lord of the Rings One Ring Earrings", isUnder20: true, type: "geeky" },
    { name: "Doctor Who Adipose Stress Toy", isUnder20: true, type: "geeky" },
    { name: "Star Wars Death Star Bluetooth Speaker", isUnder20: false, type: "geeky" },
    { name: "Harry Potter Hogwarts Crest Backpack", isUnder20: false, type: "geeky" },
    { name: "Super Mario Bros Question Block Money Box", isUnder20: true, type: "geeky" },
    { name: "Marvel Comics Avengers Desk Lamp", isUnder20: false, type: "geeky" },
    { name: "Star Trek USS Enterprise 3D Crystal Puzzle", isUnder20: true, type: "geeky" },
    { name: "The Big Bang Theory Soft Kitty Plush Toy", isUnder20: true, type: "geeky" },
    { name: "Doctor Who Tardis USB Hub", isUnder20: true, type: "geeky" },
    { name: "Eevee Plush Toy", isUnder20: true, type: "geeky" },
    { name: "Pokémon Kanto Map Poster", isUnder20: true, type: "geeky" },
    { name: "Pokémon Poké Ball Shaped Mug", isUnder20: true, type: "geeky" },
    { name: "Bulbasaur Planter Pot", isUnder20: true, type: "geeky" },
    { name: "D&D Player's Handbook", isUnder20: false, type: "geeky" },
    { name: "Dungeon Master Screen", isUnder20: false, type: "geeky" },
    { name: "Set of 7 D&D Dice", isUnder20: true, type: "geeky" },
    { name: "Critical Hit Candle", isUnder20: true, type: "geeky" },
    { name: "D&D T-Shirt", isUnder20: true, type: "geeky" },
  ];

export default giftData